version: '3'
services:
  postgres:
    image: postgres:11.0
    hostname: localhost
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
  app:
    ports:
      - "8080:8080"
volumes:
  db-data: